### ISSUE TITLE
var io = require('socket.io') or other package crash in android 

### ISSUE THREAD

**Issue by adhavalboy** [JaneaSystems/nodejs-mobile-samples#25]
var io = require('socket.io') or other package crash in android 
```
2020-02-06 15:35:03.846 4351-4600/? E/NetdEventListenerService: handleMessage: { when=-1ms what=10001 obj=com.android.server.connectivity.NetdEventListenerService$DnsResultParams@c9f9908 target=com.android.server.connectivity.NetdEventListenerService$DnsEventHandler }
2020-02-06 15:35:03.860 5707-5707/? E/pageboostd: Received HALT command code 2
2020-02-06 15:35:03.862 4351-4404/? E/DecorView: mWindow.mActivityCurrentConfig is null
2020-02-06 15:35:04.167 3917-3917/? E/Layer: [Surface(name=AppWindowToken{70ad071 token=Token{bc9e18 ActivityRecord{637938a u0 com.sec.android.app.launcher/.activities.LauncherActivity t4}}})/@0x1d03bcb - animation-leash#0] No local sync point found
2020-02-06 15:35:04.167 3917-3917/? E/Layer: [Surface(name=AppWindowToken{c7c17b7 token=Token{870feb6 ActivityRecord{633651 u0 com.yourorg.sample/.MainActivity t49}}})/@0x7e68120 - animation-leash#0] No local sync point found
2020-02-06 15:35:04.167 3917-3917/? E/Layer: [Surface(name=242bc97 com.android.systemui.ImageWallpaper)/@0x230bfb6 - animation-leash#0] No local sync point found
2020-02-06 15:35:04.171 3917-5134/? E/BufferQueueProducer: [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity$_6743#0] disconnect: not connected (req=1)
2020-02-06 15:35:04.188 3864-3864/? E/audit: type=1400 audit(1580983504.185:699): avc:  denied  { ioctl } for  pid=19082 comm="Thread-6" path="/dev/pmsg0" dev="tmpfs" ino=30 ioctlcmd=5451 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:pmsg_device:s0 tclass=chr_file permissive=0 SEPF_SM-A205U_10_0008 audit_filtered
2020-02-06 15:35:04.188 3864-3864/? E/audit: type=1300 audit(1580983504.185:699): arch=c00000b7 syscall=29 success=no exit=-13 a0=4 a1=5451 a2=1 a3=740ce8aff0 items=0 ppid=3879 pid=19082 auid=4294967295 uid=10216 gid=10216 euid=10216 suid=10216 fsuid=10216 egid=10216 sgid=10216 fsgid=10216 tty=(none) ses=4294967295 comm="Thread-6" exe="/system/bin/app_process64" subj=u:r:untrusted_app_25:s0:c512,c768 key=(null)
2020-02-06 15:35:04.189 3864-3864/? E/audit: type=1327 audit(1580983504.185:699): proctitle="com.yourorg.sample"
2020-02-06 15:35:04.189 3864-3864/? E/audit: type=1400 audit(1580983504.185:700): avc:  denied  { ioctl } for  pid=19082 comm="Thread-6" path="/sys/kernel/debug/tracing/trace_marker" dev="tracefs" ino=2207 ioctlcmd=5451 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:debugfs_trace_marker:s0 tclass=file permissive=0 SEPF_SM-A205U_10_0008 audit_filtered
2020-02-06 15:35:04.355 5707-5707/? E/pageboostd: Received HALT command code 2
2020-02-06 15:35:04.417 4351-4404/? E/WindowManager: win=Window{f99271c u0 Splash Screen com.yourorg.sample EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1199 com.android.server.wm.AppWindowToken.destroySurfaces:1180 com.android.server.wm.WindowState.onExitAnimationDone:4990 com.android.server.wm.WindowStateAnimator.onAnimationFinished:284 com.android.server.wm.WindowState.onAnimationFinished:5431 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:100 
2020-02-06 15:35:04.423 4351-5493/? E/WindowManager: win=Window{ece254e u0 com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1199 com.android.server.wm.AppWindowToken.destroySurfaces:1180 com.android.server.wm.AppWindowToken.notifyAppStopped:1235 com.android.server.wm.ActivityRecord.activityStoppedLocked:2608 com.android.server.wm.ActivityTaskManagerService.activityStopped:2375 android.app.IActivityTaskManager$Stub.onTransact:2180 android.os.Binder.execTransactInternal:1021 
2020-02-06 15:35:05.779 4351-4530/? E/InputDispatcher: channel '9385405 com.yourorg.sample/com.yourorg.sample.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-02-06 15:35:05.822 4351-4402/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{9385405 u0 com.yourorg.sample/com.yourorg.sample.MainActivity}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:527)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:797)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3599)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5151)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2020-02-06 15:35:05.833 6743-6743/? E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-02-06 15:35:05.838 5707-5707/? E/pageboostd: Received HALT command code 2
2020-02-06 15:35:05.842 11496-11572/? E/PBSessionCacheImpl: sessionId[50561523588709657] not persisted.
2020-02-06 15:35:05.866 6743-6743/? E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-02-06 15:35:06.997 3914-4262/? E/NativeSemDvfsCpuManager: release:: Start
2020-02-06 15:35:06.997 3914-4262/? E/NativeSemDvfsCpuManager: release():: mIsAcquired = 1 , mName = CPU  , mTagName : AudioFlinger 
2020-02-06 15:35:07.000 3914-4262/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseDVFSLock() 
2020-02-06 15:35:07.000 3914-4262/? E/NativeSemDvfsCpuManager: release:: End
2020-02-06 15:35:07.363 4351-4680/? E/Pageboost: ioinfo read failed
2020-02-06 15:35:17.906 6743-6743/? E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-02-06 15:35:17.934 19150-19150/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-02-06 15:35:17.936 19150-19150/? E/Zygote: accessInfo : 1
2020-02-06 15:35:17.943 6743-6743/? E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2020-02-06 15:35:17.955 19150-19150/? E/droid.daemonap: Not starting debugger since process cannot load the jdwp agent.
2020-02-06 15:35:18.320 19150-19150/? E/[WEATHER]WeatherNotificationManager(39): {[DF896475F7F963940EC459D256451CAD57675874194BEA510AF7DE330E9BDFF0AD65395FA17155B625F8CFFF589E49134D573246A8B9D038DB2C000EFC8F2665A1DFC422444373332C0EFAF55FC4C245]}
2020-02-06 15:35:29.794 4351-4869/? E/Watchdog: !@Sync 379 [2020-02-06 10:05:29.794] FD count : 541, wdog_way : softdog
2020-02-06 15:35:34.168 3917-5134/? E/BufferQueueProducer: [ColorFade#0] disconnect: not connected (req=1)
2020-02-06 15:35:34.407 3894-3946/? E/display: Need to check S3CFB power mode ioctl : 25
2020-02-06 15:35:34.468 4727-4727/? E/ActivityThread: Failed to find provider info for com.samsung.android.app.aodservice.provider
2020-02-06 15:35:34.558 4727-4727/? E/LSO_LSOInterface: LSO Service is not yet ready!!!
2020-02-06 15:35:34.621 4351-4524/? E/MotionRecognitionService:  handler : SCREEN_OFF end 
2020-02-06 15:35:34.643 3917-5134/? E/BufferQueueProducer: [StatusBar$_4727#0] disconnect: not connected (req=1)
2020-02-06 15:35:34.650 429-446/? E/BtGatt.ContextMap: remove() - removed: 6
2020-02-06 15:35:34.659 429-513/? E/BtGatt.GattService: [GSIM LOG]: gsimLogHandler, msg: MESSAGE_SCAN_STOP, appName: android.uid.system, scannerId: 6, reportDelayMillis=0
2020-02-06 15:35:34.688 3917-4361/? E/BufferQueueProducer: [NavigationBar0$_4727#0] disconnect: not connected (req=1)
2020-02-06 15:35:34.691 4351-5840/? E/WindowManager: win=Window{f3a437a u0 NavigationBar0} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2685 com.android.server.wm.WindowManagerService.relayoutWindow:2438 com.android.server.wm.Session.relayout:202 android.view.IWindowSession$Stub.onTransact:708 com.android.server.wm.Session.onTransact:142 android.os.Binder.execTransactInternal:1021 android.os.Binder.execTransact:994 
2020-02-06 15:35:34.731 4727-4727/? E/LSO_LSOInterface: LSO Service is not yet ready!!!
2020-02-06 15:35:34.795 6743-6743/? E/ViewRootImpl@fb23d68[LauncherActivity]: Surface is not valid.
2020-02-06 15:35:34.814 6743-6743/? E/ViewRootImpl@fb23d68[LauncherActivity]: Surface is not valid.
2020-02-06 15:35:34.838 3902-3902/? E/SecHAL: nfc_hal_write: [Cmd]Send EVT data_sending_flag = true, return size=4!!
2020-02-06 15:35:34.866 3902-1733/? E/SecHAL: nfc_data_callback: [Cmd]Received a response packet : data_sending_flag = false!!
2020-02-06 15:35:34.867 3902-3902/? E/SecHAL: nfc_hal_write: [Cmd]Send EVT data_sending_flag = true, return size=4!!
2020-02-06 15:35:34.870 3902-1733/? E/SecHAL: nfc_data_callback: [Cmd]Received a response
```

**Comment by introspection3** [comment]
@adhavalboy why you close it

**Comment by adhavalboy** [comment]
i solved it so close it
